spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_test?characterEncoding=utf8&serverTimezone=America/Chicago
    username: root
    password: lxkkxl
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #控制台显示sql
      show-sql: true
server:
  port: 8090
